/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/auth/Cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/auth/Login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/newpw`; params?: Router.UnknownInputParams; } | { pathname: `/auth/pwconfirm`; params?: Router.UnknownInputParams; } | { pathname: `/auth/RecuperarSenha`; params?: Router.UnknownInputParams; } | { pathname: `/chat/chatPage`; params?: Router.UnknownInputParams; } | { pathname: `/home/home`; params?: Router.UnknownInputParams; } | { pathname: `/reservas/reserva`; params?: Router.UnknownInputParams; } | { pathname: `/reservas/reservaFinish`; params?: Router.UnknownInputParams; } | { pathname: `/user/changePw`; params?: Router.UnknownInputParams; } | { pathname: `/user/confirmNewPw`; params?: Router.UnknownInputParams; } | { pathname: `/user/editUser`; params?: Router.UnknownInputParams; } | { pathname: `/user/MinhasReservas`; params?: Router.UnknownInputParams; } | { pathname: `/user/pwCode`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/reservas/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/user/[UserId]`, params: Router.UnknownInputParams & { UserId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/Cadastro`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/Login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/newpw`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/pwconfirm`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/RecuperarSenha`; params?: Router.UnknownOutputParams; } | { pathname: `/chat/chatPage`; params?: Router.UnknownOutputParams; } | { pathname: `/home/home`; params?: Router.UnknownOutputParams; } | { pathname: `/reservas/reserva`; params?: Router.UnknownOutputParams; } | { pathname: `/reservas/reservaFinish`; params?: Router.UnknownOutputParams; } | { pathname: `/user/changePw`; params?: Router.UnknownOutputParams; } | { pathname: `/user/confirmNewPw`; params?: Router.UnknownOutputParams; } | { pathname: `/user/editUser`; params?: Router.UnknownOutputParams; } | { pathname: `/user/MinhasReservas`; params?: Router.UnknownOutputParams; } | { pathname: `/user/pwCode`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/reservas/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/user/[UserId]`, params: Router.UnknownOutputParams & { UserId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/auth/Cadastro${`?${string}` | `#${string}` | ''}` | `/auth/Login${`?${string}` | `#${string}` | ''}` | `/auth/newpw${`?${string}` | `#${string}` | ''}` | `/auth/pwconfirm${`?${string}` | `#${string}` | ''}` | `/auth/RecuperarSenha${`?${string}` | `#${string}` | ''}` | `/chat/chatPage${`?${string}` | `#${string}` | ''}` | `/home/home${`?${string}` | `#${string}` | ''}` | `/reservas/reserva${`?${string}` | `#${string}` | ''}` | `/reservas/reservaFinish${`?${string}` | `#${string}` | ''}` | `/user/changePw${`?${string}` | `#${string}` | ''}` | `/user/confirmNewPw${`?${string}` | `#${string}` | ''}` | `/user/editUser${`?${string}` | `#${string}` | ''}` | `/user/MinhasReservas${`?${string}` | `#${string}` | ''}` | `/user/pwCode${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/auth/Cadastro`; params?: Router.UnknownInputParams; } | { pathname: `/auth/Login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/newpw`; params?: Router.UnknownInputParams; } | { pathname: `/auth/pwconfirm`; params?: Router.UnknownInputParams; } | { pathname: `/auth/RecuperarSenha`; params?: Router.UnknownInputParams; } | { pathname: `/chat/chatPage`; params?: Router.UnknownInputParams; } | { pathname: `/home/home`; params?: Router.UnknownInputParams; } | { pathname: `/reservas/reserva`; params?: Router.UnknownInputParams; } | { pathname: `/reservas/reservaFinish`; params?: Router.UnknownInputParams; } | { pathname: `/user/changePw`; params?: Router.UnknownInputParams; } | { pathname: `/user/confirmNewPw`; params?: Router.UnknownInputParams; } | { pathname: `/user/editUser`; params?: Router.UnknownInputParams; } | { pathname: `/user/MinhasReservas`; params?: Router.UnknownInputParams; } | { pathname: `/user/pwCode`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | `/reservas/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/user/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/reservas/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/user/[UserId]`, params: Router.UnknownInputParams & { UserId: string | number; } };
    }
  }
}
